# Generated by Django 6.0.6 on 2026-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default='DOC-0000', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
